# Generated by Django 6.0.7 on 2026-07-15 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_reelshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
