# Generated by Django 6.0.7 on 2026-09-05 13:09

import reels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_reel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(storage=reels.models.reel_video_storage, upload_to='reels/'),
        ),
    ]