# Generated by Django 6.0.7 on 2026-07-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_shared_post'),
        ('posts', '0003_alter_savedpost_post_alter_savedpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_messages', to='posts.post'),
        ),
    ]
